### ISSUE TITLE
Can't use Usage Files methods

### ISSUE THREAD

**Issue by serginator** [cloudblue/connect-javascript-sdk#35]
Hi. I think there's needed here something like `this._usageFiles = new api.UsageFileResource(this)` to expose the usageFiles methods.

https://github.com/cloudblue/connect-javascript-sdk/blob/d4907468984b8de762f6c2075b09c7a7a75c3ab3/lib/connect/client.js#L49

**Comment by marcserrat** [comment]
Thanks @serginator! issue had been resolved
